### ISSUE TITLE
results: use subcommands instead of --action= option

### ISSUE THREAD

**Issue by padovan** [kernelci/kci-dev#65]
We want the results cmd to look like `kci-dev results summary` instead of `kci-dev results --action=summary` , but we didn't figure out yet how to do that with Python [Click](https://click.palletsprojects.com/en/stable/#documentation).

Related to #57

**Comment by aliceinwire** [comment]
why don't use click choice options https://click.palletsprojects.com/en/stable/options/#choice-options

**Comment by aliceinwire** [comment]
I will send a draft with this

**Comment by aliceinwire** [comment]
Draft: https://github.com/kernelci/kci-dev/pull/70

**Comment by aliceinwire** [comment]
fixed by https://github.com/kernelci/kci-dev/pull/70
